<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>scopeName</key>
		<string>markdown.matlab.codeblock</string>
		<key>fileTypes</key>
		<array />
		<key>injectionSelector</key>
		<string>L:text.html.markdown</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>include</key>
				<string>#matlab-code-block</string>
			</dict>
		</array>
		<key>repository</key>
		<dict>
			<key>matlab-code-block</key>
			<dict>
				<key>begin</key>
				<string>(^|\G)(\s*)(\`{3,}|~{3,})\s*(?i:(matlab)(\s+[^`~]*)?$)</string>
				<key>name</key>
				<string>markup.fenced_code.block.markdown</string>
				<key>end</key>
				<string>(^|\G)(\2|\s{0,3})(\3)\s*$</string>
				<key>beginCaptures</key>
				<dict>
					<key>3</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.markdown</string>
					</dict>
					<key>4</key>
					<dict>
						<key>name</key>
						<string>fenced_code.block.language.markdown</string>
					</dict>
					<key>5</key>
					<dict>
						<key>name</key>
						<string>fenced_code.block.language.attributes.markdown</string>
					</dict>
				</dict>
				<key>endCaptures</key>
				<dict>
					<key>3</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.markdown</string>
					</dict>
				</dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>(^|\G)(\s*)(.*)</string>
						<key>while</key>
						<string>(^|\G)(?!\s*([`~]{3,})\s*$)</string>
						<key>contentName</key>
						<string>meta.embedded.block.matlab</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>source.matlab</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
		</dict>
	</dict>
</plist>
