<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>m</string>
		</array>
		<key>keyEquivalent</key>
		<string>^~M</string>
		<key>name</key>
		<string>Read-write operations with variables (MATLAB)</string>
		<key>scopeName</key>
		<string>readwrite.matlab.injection</string>
		<key>injectionSelector</key>
		<string>source.matlab -comment -support -string -interpolation -entity.name -source.shell</string>
		<key>uuid</key>
		<string>0C9C0597-80CF-47AF-B742-DD4260FEC77E</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>include</key>
				<string>#readwrite_operations</string>
			</dict>
		</array>
		<key>repository</key>
		<dict>
		</dict>
	</dict>
</plist>
